### ISSUE TITLE
big issue

### ISSUE THREAD

**Issue by seenu19** [newbdez33/paopao#17]
![screenshot 2014-02-15 12 08 33](https://f.cloud.github.com/assets/5083278/2177501/c965b98a-9620-11e3-96e7-22e5199dcb58.png)

if i changed the row or column numbers to different. (for eg:-  i changed 8_7 from 7_7  in your prefix.pch) its crashed. i atatched screeshot

**Comment by newbdez33** [comment]
Well. I see this issue. but this game is designed for 8_7. 
So there is no concerned in code other that 8_7.

**Comment by seenu19** [comment]
hi,
if am planing to do for 8 \* 7 then where should i change code?. to get work this... plz give me some help to work this.
